# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpdesk', '0020_auto_20170904_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(unique=True, verbose_name='Ключ')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Имя таблицы')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Crew', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Динамическая таблица',
                'verbose_name_plural': 'Динамические таблицы',
                'ordering': ['name'],
            },
        ),
    ]
