# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyntable', '0002_table_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(unique=True, verbose_name='Ключ')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Наименование поля')),
                ('type', models.IntegerField(choices=[(1, 'Число'), (2, 'Строка'), (3, 'Дата'), (4, 'IP'), (5, 'Пароль')], default=2, verbose_name='Тип поля')),
                ('order', models.IntegerField(default=10, verbose_name='Сортировка')),
                ('deleted', models.BooleanField(default=False, verbose_name='Запись удалена')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyntable.Table', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Поле таблицы',
                'verbose_name_plural': 'Поля таблицы',
                'ordering': ['name'],
            },
        ),
    ]
