# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyntable', '0004_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=255, verbose_name='Значение')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyntable.Field', verbose_name='Поле')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dyntable.Index', verbose_name='Номер строки')),
            ],
            options={
                'verbose_name': 'Значение поля',
                'verbose_name_plural': 'Значения полей',
                'ordering': ['index', 'field'],
            },
        ),
    ]
