# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('crew_user_limit', models.IntegerField(default=0)),
                ('start_task', models.IntegerField(default=0)),
                ('incident_time_one', models.IntegerField(default=0)),
                ('incident_time_two', models.IntegerField(default=0)),
                ('request_time_one', models.IntegerField(default=0)),
                ('request_time_two', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'Crews',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CrewUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Administrator'), (1, 'Dispatcher'), (2, 'Operator')], default=2)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Crew')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crew user',
                'verbose_name_plural': 'Crew users',
                'ordering': ['crew', 'user'],
            },
        ),
    ]
