# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
