# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_crew_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewusers',
            options={'ordering': ['type', 'user'], 'verbose_name': 'Crew user', 'verbose_name_plural': 'Crew users'},
        ),
    ]
