# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 05:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_auto_20170803_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Наименование')),
                ('time1', models.IntegerField(default=10, verbose_name='Время первой реакции')),
                ('time2', models.IntegerField(default=48, verbose_name='Время на завершение заявки')),
                ('time3', models.IntegerField(default=480, verbose_name='Время провала заявки')),
                ('unit', models.CharField(default='', max_length=50, verbose_name='Единица измерения')),
                ('deleted', models.BooleanField(default=False, verbose_name='Услуга удалена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['crew', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='crew',
            name='crew_user_limit',
            field=models.IntegerField(default=0, verbose_name='Ограничение на количество членов команды'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Команда удалена'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название команды'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель команды'),
        ),
        migrations.AlterField(
            model_name='crewusers',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Crew', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='crewusers',
            name='type',
            field=models.IntegerField(choices=[(0, 'Administrator'), (1, 'Dispatcher'), (2, 'Operator')], default=2, verbose_name='Уровеь доступа'),
        ),
        migrations.AlterField(
            model_name='crewusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='crewservice',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Crew', verbose_name='Команда'),
        ),
    ]
