# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_auto_20170807_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='fine1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Штраф за невыполнение заявки в срок'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='fine2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Штраф за просроченную заявку'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='prepay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Предоплата'),
        ),
    ]
