# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_crewusers_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Наименование')),
                ('time_factor', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Коэффициент времени выполнения')),
                ('cost_factor', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Коэффициент стоимости')),
                ('default', models.BooleanField(default=False, verbose_name='Выбрано по умолчанию')),
                ('deleted', models.BooleanField(default=False, verbose_name='Приоритет удален')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Crew', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Приоритет выполнения',
                'verbose_name_plural': 'Приоритеты выполнения',
                'ordering': ['crew', 'name'],
            },
        ),
    ]
