# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_taskpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewservice',
            name='auto_wait_status',
            field=models.BooleanField(default=False, verbose_name='Заявка автоматически переводится в статус "В ожидании"'),
        ),
    ]
