# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0010_crewevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=200, verbose_name='Уникальный ключ')),
                ('type', models.IntegerField(choices=[(0, 'Normal'), (1, 'Incident'), (2, 'Subscribe')], default=0, verbose_name='Тип заявки')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Waiting'), (2, 'Paused'), (3, 'In work'), (4, 'Canceled'), (5, 'Finished'), (6, 'Closed')], default=0, verbose_name='Статус заявки')),
                ('description', models.TextField(default='', verbose_name='Текстовое описание')),
                ('date_in', models.DateTimeField(verbose_name='Дата подачи заявки')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания подписки')),
                ('date_finish', models.DateTimeField(verbose_name='Дата выполнения заявки')),
                ('date_close', models.DateTimeField(verbose_name='Дата закрытия заявки')),
                ('contact_name', models.CharField(default='', max_length=200, verbose_name='Имя контакта')),
                ('contact_email', models.CharField(default='', max_length=200, verbose_name='Электронный адрес контакта')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Количество оказанной услуги')),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Штраф к стоимости, накладываемый администратором')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Crew', verbose_name='Команда')),
                ('dispatcher_close', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_close', to=settings.AUTH_USER_MODEL, verbose_name='Диспетчер, закрывший заявку')),
                ('dispatcher_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_in', to=settings.AUTH_USER_MODEL, verbose_name='Диспетчер, обработавший новую заявку')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator', to=settings.AUTH_USER_MODEL, verbose_name='Оператор, выполнивший заявку')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.TaskPriority', verbose_name='Приоритет заявки')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.CrewService', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-date_in'],
            },
        ),
        migrations.AlterModelOptions(
            name='crewevent',
            options={'ordering': ['-date'], 'verbose_name': 'Событие в команде', 'verbose_name_plural': 'События в команде'},
        ),
    ]
