# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 06:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0012_crewservice_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время события')),
                ('ip', models.GenericIPAddressField(default='', verbose_name='IP адрес пользователя')),
                ('host', models.CharField(default='', max_length=60, verbose_name='Хост пользователя')),
                ('user_agent', models.CharField(default='', max_length=200, verbose_name='Идентификатор браузера')),
                ('message', models.TextField(default='', verbose_name='Событие')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.CrewTask', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие в заявке',
                'verbose_name_plural': 'События в заявке',
                'ordering': ['-date'],
            },
        ),
    ]
