# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpcrew.helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_taskevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=helpcrew.helpdesk.models.TaskFiles.file_path, verbose_name='Вложение')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.CrewTask', verbose_name='Заявка')),
            ],
        ),
    ]
