# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0017_auto_20170830_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='holidays',
            field=models.TextField(default='', verbose_name='Праздники'),
        ),
        migrations.AddField(
            model_name='crew',
            name='launch_days',
            field=models.CharField(default='0,1,2,3,4', max_length=15, verbose_name='Дни обеденного перерыва'),
        ),
        migrations.AddField(
            model_name='crew',
            name='launch_end_time',
            field=models.IntegerField(default=14, verbose_name='Конец обеденного перерыва'),
        ),
        migrations.AddField(
            model_name='crew',
            name='launch_start_time',
            field=models.IntegerField(default=13, verbose_name='Начало обеденного перерыва'),
        ),
        migrations.AddField(
            model_name='crew',
            name='work_days',
            field=models.CharField(default='0,1,2,3,4', max_length=15, verbose_name='Рабочие дни'),
        ),
        migrations.AddField(
            model_name='crew',
            name='work_end_time',
            field=models.IntegerField(default=18, verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='crew',
            name='work_start_time',
            field=models.IntegerField(default=9, verbose_name='Начало рабочего дня'),
        ),
    ]
