# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_remove_crew_launch_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='work_days',
        ),
        migrations.AddField(
            model_name='crew',
            name='work_day_0',
            field=models.BooleanField(default=True, verbose_name='Рабочий день 0'),
        ),
        migrations.AddField(
            model_name='crew',
            name='work_day_1',
            field=models.BooleanField(default=True, verbose_name='Рабочий день 1'),
        ),
        migrations.AddField(
            model_name='crew',
            name='work_day_2',
            field=models.BooleanField(default=True, verbose_name='Рабочий день 2'),
        ),
        migrations.AddField(
            model_name='crew',
            name='work_day_3',
            field=models.BooleanField(default=True, verbose_name='Рабочий день 3'),
        ),
        migrations.AddField(
            model_name='crew',
            name='work_day_4',
            field=models.BooleanField(default=True, verbose_name='Рабочий день 4'),
        ),
        migrations.AddField(
            model_name='crew',
            name='work_day_5',
            field=models.BooleanField(default=False, verbose_name='Рабочий день 5'),
        ),
        migrations.AddField(
            model_name='crew',
            name='work_day_6',
            field=models.BooleanField(default=False, verbose_name='Рабочий день 6'),
        ),
    ]
