# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0020_auto_20170904_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='launch_end_time',
            field=models.CharField(default='14:00', max_length=5, verbose_name='Конец обеденного перерыва'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='launch_start_time',
            field=models.CharField(default='13:00', max_length=5, verbose_name='Начало обеденного перерыва'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_end_time',
            field=models.CharField(default='18:00', max_length=5, verbose_name='Конец рабочего дня'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_start_time',
            field=models.CharField(default='9:00', max_length=5, verbose_name='Начало рабочего дня'),
        ),
    ]
