# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0022_auto_20170912_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskpriority',
            options={'ordering': ['crew', 'time_factor'], 'verbose_name': 'Приоритет выполнения', 'verbose_name_plural': 'Приоритеты выполнения'},
        ),
    ]
