# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0023_auto_20170916_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewevent',
            name='host',
        ),
        migrations.RemoveField(
            model_name='taskevent',
            name='host',
        ),
    ]
