# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import helpcrew.helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0024_auto_20170923_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=helpcrew.helpdesk.models.Crew.logo_path, verbose_name='Logo'),
        ),
    ]
