# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0026_auto_20170926_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='crew',
            name='user_page',
            field=models.TextField(default='', verbose_name='Текст для пользователя'),
        ),
    ]
