# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0027_auto_20170926_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='Пароль для подачи заявок'),
        ),
    ]
