# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0028_crew_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Команда видна в списке команд на главной странице'),
        ),
    ]
