# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0031_auto_20170929_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewtask',
            name='date_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала выполнения заявки'),
        ),
    ]
