# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0033_crew_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AddField(
            model_name='crewtask',
            name='commentary',
            field=models.TextField(default='', verbose_name='Комментарий к заявке'),
        ),
    ]
