# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0035_auto_20171025_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewusers',
            name='task_show_canceled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='crewusers',
            name='task_show_closed',
            field=models.BooleanField(default=True),
        ),
    ]
