# Generated by Django 2.2.3 on 2019-07-17 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpcrew.helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0037_auto_20171029_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Crew', 'verbose_name_plural': 'Crews'},
        ),
        migrations.AlterModelOptions(
            name='crewevent',
            options={'ordering': ['-date'], 'verbose_name': 'Crew event', 'verbose_name_plural': 'Crew events'},
        ),
        migrations.AlterModelOptions(
            name='crewservice',
            options={'ordering': ['crew', 'name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='crewtask',
            options={'ordering': ['-date_in'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='crewusers',
            options={'ordering': ['type', 'user'], 'verbose_name': 'Crew user', 'verbose_name_plural': 'Crew users'},
        ),
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'ordering': ['service', 'start_date'], 'verbose_name': 'Service price', 'verbose_name_plural': 'Services price'},
        ),
        migrations.AlterModelOptions(
            name='taskevent',
            options={'ordering': ['-date'], 'verbose_name': 'Task event', 'verbose_name_plural': 'Task events'},
        ),
        migrations.AlterModelOptions(
            name='taskfiles',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelOptions(
            name='taskpriority',
            options={'ordering': ['crew', 'time_factor'], 'verbose_name': 'Execution priority', 'verbose_name_plural': 'Execution priorities'},
        ),
        migrations.AlterModelOptions(
            name='taskusers',
            options={'ordering': ['task', 'user', 'type'], 'verbose_name': 'Task user', 'verbose_name_plural': 'Task users'},
        ),
        migrations.AlterField(
            model_name='crew',
            name='crew_user_limit',
            field=models.IntegerField(default=0, verbose_name='Limit on the number of crew members'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Crew is deleted'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='holidays',
            field=models.TextField(default='', verbose_name='Holidays'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Show crew in crew list'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='lunch_end_time',
            field=models.CharField(default='14:00', max_length=5, verbose_name='The end of the lunch break'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='lunch_start_time',
            field=models.CharField(default='13:00', max_length=5, verbose_name='Start of lunch break'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Crew name'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='order',
            field=models.IntegerField(default=10000, verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='Password for add tasks'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='Crew link'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Crew creator'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='user_page',
            field=models.TextField(default='', verbose_name='Description for user'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_day_0',
            field=models.BooleanField(default=True, verbose_name='Working day 0'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_day_1',
            field=models.BooleanField(default=True, verbose_name='Working day 1'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_day_2',
            field=models.BooleanField(default=True, verbose_name='Working day 2'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_day_3',
            field=models.BooleanField(default=True, verbose_name='Working day 3'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_day_4',
            field=models.BooleanField(default=True, verbose_name='Working day 4'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_day_5',
            field=models.BooleanField(default=False, verbose_name='Working day 5'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_day_6',
            field=models.BooleanField(default=False, verbose_name='Working day 6'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_end_time',
            field=models.CharField(default='18:00', max_length=5, verbose_name='The end of the working day'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='work_start_time',
            field=models.CharField(default='9:00', max_length=5, verbose_name='The begining of the work day'),
        ),
        migrations.AlterField(
            model_name='crewevent',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.Crew', verbose_name='Crew'),
        ),
        migrations.AlterField(
            model_name='crewevent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Event time'),
        ),
        migrations.AlterField(
            model_name='crewevent',
            name='ip',
            field=models.GenericIPAddressField(default='', verbose_name='User ip address'),
        ),
        migrations.AlterField(
            model_name='crewevent',
            name='message',
            field=models.TextField(default='', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='crewevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='crewevent',
            name='user_agent',
            field=models.CharField(default='', max_length=200, verbose_name='User agent name'),
        ),
        migrations.AlterField(
            model_name='crewservice',
            name='auto_wait_status',
            field=models.BooleanField(default=False, verbose_name='The task is automatically transferred to the status of "Pending"'),
        ),
        migrations.AlterField(
            model_name='crewservice',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.Crew', verbose_name='Crew'),
        ),
        migrations.AlterField(
            model_name='crewservice',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Service is deleted'),
        ),
        migrations.AlterField(
            model_name='crewservice',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Service name'),
        ),
        migrations.AlterField(
            model_name='crewservice',
            name='template',
            field=models.TextField(default='', verbose_name='Task template'),
        ),
        migrations.AlterField(
            model_name='crewservice',
            name='time1',
            field=models.IntegerField(default=10, verbose_name='First reaction time'),
        ),
        migrations.AlterField(
            model_name='crewservice',
            name='time2',
            field=models.IntegerField(default=48, verbose_name='Time to complete the task'),
        ),
        migrations.AlterField(
            model_name='crewservice',
            name='time3',
            field=models.IntegerField(default=480, verbose_name='Time of failure'),
        ),
        migrations.AlterField(
            model_name='crewservice',
            name='unit',
            field=models.CharField(default='', max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='commentary',
            field=models.TextField(default='', verbose_name='Commentary'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='contact_email',
            field=models.CharField(default='', max_length=200, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='contact_name',
            field=models.CharField(default='', max_length=200, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.Crew', verbose_name='Crew'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Close date'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End of subscribe'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='date_finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End of work date'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='date_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='In date'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='date_work',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start work date'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='The fine to the cost imposed by the administrator'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.TaskPriority', verbose_name='Execution priority'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.CrewService', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Waiting'), (2, 'Paused'), (3, 'In work'), (4, 'Canceled'), (5, 'Finished'), (6, 'Closed')], default=0, verbose_name='Task status'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Incident'), (2, 'Subscribe')], default=0, verbose_name='Task type'),
        ),
        migrations.AlterField(
            model_name='crewtask',
            name='uuid',
            field=models.CharField(default='', max_length=200, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='crewusers',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.Crew', verbose_name='Crew'),
        ),
        migrations.AlterField(
            model_name='crewusers',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='User is deleted'),
        ),
        migrations.AlterField(
            model_name='crewusers',
            name='type',
            field=models.IntegerField(choices=[(0, 'Administrator'), (1, 'Dispatcher'), (2, 'Operator'), (3, 'Observer')], default=2, verbose_name='Type of user'),
        ),
        migrations.AlterField(
            model_name='crewusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Service cost'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='fine1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Fine for not completing the application on time'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='fine2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Fine for overdue application'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='prepay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Prepayment'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.CrewService', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Starting date of the price'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Event time'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='ip',
            field=models.GenericIPAddressField(default='', verbose_name='User IP address'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='message',
            field=models.TextField(default='', verbose_name='Event text'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.CrewTask', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='taskevent',
            name='user_agent',
            field=models.CharField(default='', max_length=200, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='taskfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=helpcrew.helpdesk.models.TaskFiles.file_path, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='taskfiles',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.CrewTask', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='cost_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cost factor'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.Crew', verbose_name='Crew'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Selected by default'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Priority is deleted'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Priority name'),
        ),
        migrations.AlterField(
            model_name='taskpriority',
            name='time_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Time factor'),
        ),
        migrations.AlterField(
            model_name='taskusers',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='helpdesk.CrewTask', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='taskusers',
            name='type',
            field=models.IntegerField(choices=[(0, 'OBSERVER'), (1, 'DISPATCHER'), (2, 'OPERATOR'), (3, 'RESPONSIBLE')], default=0, verbose_name='User type'),
        ),
        migrations.AlterField(
            model_name='taskusers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
