# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_from', models.CharField(default='', max_length=255)),
                ('msg_to', models.CharField(default='', max_length=255)),
                ('msg_bcc', models.CharField(default='', max_length=255)),
                ('body', models.TextField(default='')),
                ('body_alternative', models.TextField(default='')),
                ('subject', models.CharField(default='', max_length=255)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email task',
                'verbose_name_plural': 'Email tasks',
                'ordering': ['is_finished', 'added'],
            },
        ),
    ]
