# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskqueue', '0002_email_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='body_alternative',
        ),
    ]
