# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userext', '0002_auto_20170803_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interface_wide_screen',
            field=models.BooleanField(default=False, verbose_name='wide screen support'),
        ),
    ]
